export const AMERICAN_COUNTRIES = Object.entries({
  AR: 'Argentina',
  BO: 'Bolivia',
  BR: 'Brazil',
  CA: 'Canada',
  CL: 'Chile',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  DO: 'Dominican Republic',
  GT: 'Guatemala',
  GY: 'Guyana',
  HN: 'Honduras',
  HT: 'Haiti',
  MX: 'Mexico',
  NI: 'Nicaragua',
  PA: 'Panama',
  PY: 'Paraguay',
  PE: 'Peru',
  SR: 'Suriname',
  US: 'United States',
  UY: 'Uruguay',
  VE: 'Venezuela',
})
